//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiny_Engine_FNF.FridayNightFunkinDataBase {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class KeybindsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeybindsSettings defaultInstance = ((KeybindsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeybindsSettings())));
        
        public static KeybindsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25769803794")]
        public long KeyBindsAccept {
            get {
                return ((long)(this["KeyBindsAccept"]));
            }
            set {
                this["KeyBindsAccept"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55834574854")]
        public long KeyBindsPause {
            get {
                return ((long)(this["KeyBindsPause"]));
            }
            set {
                this["KeyBindsPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("98784247852")]
        public long KeyBindsLeft {
            get {
                return ((long)(this["KeyBindsLeft"]));
            }
            set {
                this["KeyBindsLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111669149758")]
        public long KeyBindsDown {
            get {
                return ((long)(this["KeyBindsDown"]));
            }
            set {
                this["KeyBindsDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("103079215170")]
        public long KeyBindsUp {
            get {
                return ((long)(this["KeyBindsUp"]));
            }
            set {
                this["KeyBindsUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("107374182447")]
        public long KeyBindsRight {
            get {
                return ((long)(this["KeyBindsRight"]));
            }
            set {
                this["KeyBindsRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61")]
        public long KeyBindsReset {
            get {
                return ((long)(this["KeyBindsReset"]));
            }
            set {
                this["KeyBindsReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("98784247852")]
        public long KeyBindsUILeft {
            get {
                return ((long)(this["KeyBindsUILeft"]));
            }
            set {
                this["KeyBindsUILeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111669149758")]
        public long KeyBindsUIDown {
            get {
                return ((long)(this["KeyBindsUIDown"]));
            }
            set {
                this["KeyBindsUIDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("103079215170")]
        public long KeyBindsUIUp {
            get {
                return ((long)(this["KeyBindsUIUp"]));
            }
            set {
                this["KeyBindsUIUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("107374182447")]
        public long KeyBindsUIRight {
            get {
                return ((long)(this["KeyBindsUIRight"]));
            }
            set {
                this["KeyBindsUIRight"] = value;
            }
        }
    }
}
